theme: minima

title: Best Foot Forward
author: Nothemba Hlongwa
email: nothemba.t.h@mail.com
description: > # this means to ignore newlines until "baseurl:"
  Fashion blog teaching you how to use fashion and art to put your best foot forward.

# social links
twitter_username: kween_rsa # DO NOT include the @ character, or else the build will fail!
github_username:  nothembah # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
